version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - branch_plugin_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.2-apache
    volumes:
      - .:/var/www/html/wp-content/plugins/branch-helper/
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

  composer:
    image: composer
    volumes:
      - .:/app

volumes:
  branch_plugin_db_data:
